port=53

listen-address=127.0.0.1,10.7.21.182
bind-interfaces

address=/app.team1.test/10.7.21.206
address=/api.team1.test/10.7.21.206

server=1.1.1.1
server=8.8.8.8

cache-size=150

log-queries
log-facility=/tmp/team1-dns.log
